### ISSUE TITLE
Passenger lights interface doesn't allow for non rgb lights

### ISSUE THREAD

**Issue by Moo-dev** [SRC-org/TCP#2]

**Comment by srpnt3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Passenger lights interface doesn't allow for non rgb lights](https://trello.com/c/IxuqiIsQ/19-passenger-lights-interface-doesnt-allow-for-non-rgb-lights)

**Comment by srpnt3** [comment]
Fixed with commit 9b7e4a9
