### ISSUE TITLE
"activate engine" on "drivetrain interface" isnt connected to anything inside of the mc

### ISSUE THREAD

**Issue by Sharp78913** [SRC-org/TCP#3]
![573090_20230410154755_1](https://user-images.githubusercontent.com/130381103/230925252-98886bb6-715d-4846-a826-c5f43abb7bab.png)

**Comment by srpnt3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["activate engine" on "drivetrain interface" isnt connected to anything inside of the mc](https://trello.com/c/7Q64fW3h/22-activate-engine-on-drivetrain-interface-isnt-connected-to-anything-inside-of-the-mc)

**Comment by srpnt3** [comment]
Fixed with commit 9b7e4a9
